
export const locations = [
    {
        id: "ulaanbaatar",
        name: "Улаанбаатар",
        soums: [],
    },

    {
        id: "arkhangai",
        name: "Архангай",
        soums: [
            { id: "battsengel", name: "Батцэнгэл" },
            { id: "bulgan", name: "Булган" },
            { id: "jargalant", name: "Жаргалант" },
            { id: "ikhtamir", name: "Ихтамир" },
            { id: "ogii_nuur", name: "Өгийнуур" },
            { id: "olziit", name: "Өлзийт" },
            { id: "ondor_ulaan", name: "Өндөр-Улаан" },
            { id: "tariat", name: "Тариат" },
            { id: "tuvshruuleh", name: "Түвшрүүлэх" },
            { id: "khairkhan", name: "Хайрхан" },
            { id: "khangai", name: "Хангай" },
            { id: "khashaat", name: "Хашаат" },
            { id: "khotont", name: "Хотонт" },
            { id: "tsakhir", name: "Цахир" },
            { id: "tsenher", name: "Цэнхэр" },
            { id: "tsetserleg", name: "Цэцэрлэг" },
            { id: "chuluut", name: "Чулуут" },
            { id: "erdenebulgan", name: "Эрдэнэбулган" },
            { id: "erdenemandal", name: "Эрдэнэмандал" },
        ],
    },
    {
        id: "bayan_olgii",
        name: "Баян-Өлгий",
        soums: [
            { id: "altantsogts", name: "Алтанцөгц" },
            { id: "altai", name: "Алтай" },
            { id: "bayannuur", name: "Баяннуур" },
            { id: "bugat", name: "Бугат" },
            { id: "bulgan", name: "Булган" },
            { id: "buyant", name: "Буянт" },
            { id: "deluun", name: "Дэлүүн" },
            { id: "nogoonnuur", name: "Ногооннуур" },
            { id: "olgii", name: "Өлгий" },
            { id: "sagsai", name: "Сагсай" },
            { id: "tolbo", name: "Толбо" },
            { id: "ulaanhus", name: "Улаанхус" },
            { id: "tsagaannuur", name: "Цагааннуур" },
            { id: "tsengel", name: "Цэнгэл" },
        ],
    },
    {
        id: "bayankhongor",
        name: "Баянхонгор",
        soums: [
            { id: "baatsagaan", name: "Баацагаан" },
            { id: "bayan_ondor", name: "Баян-Өндөр" },
            { id: "bayan_ovoo", name: "Баян-Овоо" },
            { id: "bayanbulag", name: "Баянбулаг" },
            { id: "bayangobi", name: "Баянговь" },
            { id: "bayanlig", name: "Баянлиг" },
            { id: "bayankhongor", name: "Баянхонгор" },
            { id: "bayantsagaan", name: "Баянцагаан" },
            { id: "bogd", name: "Богд" },
            { id: "bombogor", name: "Бөмбөгөр" },
            { id: "buutsagaan", name: "Бууцагаан" },
            { id: "galuut", name: "Галуут" },
            { id: "gurvanbulag", name: "Гурванбулаг" },
            { id: "jargalant", name: "Жаргалант" },
            { id: "jinst", name: "Жинст" },
            { id: "zag", name: "Заг" },
            { id: "olziit", name: "Өлзийт" },
            { id: "khureemaral", name: "Хүрээмарал" },
            { id: "shinejinst", name: "Шинэжинст" },
            { id: "erdenetsogt", name: "Эрдэнэцогт" },
        ],
    },
    {
        id: "bulgan",
        name: "Булган",
        soums: [
            { id: "bayan_agut", name: "Баян-Агт" },
            { id: "bayannuur", name: "Баяннуур" },
            { id: "bugat", name: "Бугат" },
            { id: "bulgan", name: "Булган" },
            { id: "bureghangai", name: "Бүрэгхангай" },
            { id: "gurvanbulag", name: "Гурванбулаг" },
            { id: "dashinchilen", name: "Дашинчилэн" },
            { id: "mogod", name: "Могод" },
            { id: "orkhon", name: "Орхон" },
            { id: "rashaant", name: "Рашаант" },
            { id: "saikhan", name: "Сайхан" },
            { id: "selenge", name: "Сэлэнгэ" },
            { id: "teshig", name: "Тэшиг" },
            { id: "khangal", name: "Хангал" },
            { id: "khishig_ondor", name: "Хишиг-Өндөр" },
            { id: "khutag_ondor", name: "Хутаг-Өндөр" },
            { id: "hyalganat", name: "Хялганат" }, // Tosgon
        ],
    },
    {
        id: "govi_altai",
        name: "Говь-Алтай",
        soums: [
            { id: "altai", name: "Алтай" },
            { id: "bayan_uul", name: "Баян-Уул" },
            { id: "bigel", name: "Бигэр" },
            { id: "bugat", name: "Бугат" },
            { id: "dariv", name: "Дарив" },
            { id: "delger", name: "Дэлгэр" },
            { id: "esunbulag", name: "Есөнбулаг" },
            { id: "jargalan", name: "Жаргалан" },
            { id: "taishir", name: "Тайшир" },
            { id: "tonkhil", name: "Тонхил" },
            { id: "tugrug", name: "Төгрөг" },
            { id: "haliun", name: "Халиун" },
            { id: "hohmorit", name: "Хөхморьт" },
            { id: "tsogt", name: "Цогт" },
            { id: "tseel", name: "Цээл" },
            { id: "chandmani", name: "Чандмань" },
            { id: "sharga", name: "Шарга" },
            { id: "erdene", name: "Эрдэнэ" },
        ],
    },
    {
        id: "govisumber",
        name: "Говьсүмбэр",
        soums: [
            { id: "bayantal", name: "Баянтал" },
            { id: "sumber", name: "Сүмбэр" },
            { id: "shiveegobi", name: "Шивээговь" },
        ],
    },
    {
        id: "darkhan_uul",
        name: "Дархан-Уул",
        soums: [
            { id: "darkhan", name: "Дархан" },
            { id: "orkhon", name: "Орхон" },
            { id: "khongor", name: "Хонгор" },
            { id: "sharyngol", name: "Шарынгол" }, // Tosgon included as soum
        ],
    },
    {
        id: "dornogovi",
        name: "Дорноговь",
        soums: [
            { id: "airag", name: "Айраг" },
            { id: "altanshiree", name: "Алтанширээ" },
            { id: "dalanjargalan", name: "Даланжаргалан" },
            { id: "delgereh", name: "Дэлгэрэх" },
            { id: "zamiin_uud", name: "Замын-Үүд" }, // Tosgon/Border
            { id: "zuunbayan", name: "Зүүнбаян" }, // Tosgon
            { id: "ihhet", name: "Иххэт" },
            { id: "mandakh", name: "Мандах" },
            { id: "orgon", name: "Өргөн" },
            { id: "saikhandulaan", name: "Сайхандулаан" },
            { id: "sainshand", name: "Сайншанд" },
            { id: "ulanbadrakh", name: "Улаанбадрах" },
            { id: "khatanbulag", name: "Хатанбулаг" },
            { id: "khovsgol", name: "Хөвсгөл" },
            { id: "erdene", name: "Эрдэнэ" },
        ],
    },
    {
        id: "dornod",
        name: "Дорнод",
        soums: [
            { id: "bayandon", name: "Баяндун" },
            { id: "bayantumen", name: "Баянтүмэн" },
            { id: "bayan_uul", name: "Баян-Уул" },
            { id: "bulgan", name: "Булган" },
            { id: "gurvanzagal", name: "Гурванзагал" },
            { id: "dashbalbar", name: "Дашбалбар" },
            { id: "matad", name: "Матад" },
            { id: "sergelen", name: "Сэргэлэн" },
            { id: "khalkhgol", name: "Халхгол" },
            { id: "kherlen", name: "Хэрлэн" },
            { id: "kholonbuir", name: "Хөлөнбуйр" },
            { id: "tsagaan_ovoo", name: "Цагаан-Овоо" },
            { id: "choibalsan", name: "Чойбалсан" },
            { id: "chuluunkhoroot", name: "Чулуунхороот" },
        ],
    },
    {
        id: "dundgovi",
        name: "Дундговь",
        soums: [
            { id: "adaatsag", name: "Адаацаг" },
            { id: "bayanjargalan", name: "Баянжаргалан" },
            { id: "gobi_ugtaal", name: "Говь-Угтаал" },
            { id: "gurvansaikhan", name: "Гурвансайхан" },
            { id: "delgerhangai", name: "Дэлгэрхангай" },
            { id: "delgertsogt", name: "Дэлгэрцогт" },
            { id: "derene", name: "Дэрэн" },
            { id: "luus", name: "Луус" },
            { id: "olziit", name: "Өлзийт" },
            { id: "ondorshil", name: "Өндөршил" },
            { id: "saikhan_ovoo", name: "Сайхан-Овоо" },
            { id: "saintsagaan", name: "Сайнцагаан" },
            { id: "khuld", name: "Хулд" },
            { id: "tsagaandelger", name: "Цагаандэлгэр" },
            { id: "erdenedalai", name: "Эрдэнэдалай" },
        ],
    },
    {
        id: "zavkhan",
        name: "Завхан",
        soums: [
            { id: "aldarkhaan", name: "Алдархаан" },
            { id: "asgat", name: "Асгат" },
            { id: "bayantes", name: "Баянтэс" },
            { id: "bayankhairkhan", name: "Баянхайрхан" },
            { id: "durvuljin", name: "Дөрвөлжин" },
            { id: "zavkhanmandal", name: "Завханмандал" },
            { id: "ider", name: "Идэр" },
            { id: "ih_uul", name: "Их-Уул" },
            { id: "nomrog", name: "Нөмрөг" },
            { id: "otgon", name: "Отгон" },
            { id: "santmargats", name: "Сантмаргац" },
            { id: "songino", name: "Сонгино" },
            { id: "todentsengel", name: "Тосонцэнгэл" },
            { id: "tudevtei", name: "Түдэвтэй" },
            { id: "telmen", name: "Тэлмэн" },
            { id: "tes", name: "Тэс" },
            { id: "uliastai", name: "Улиастай" },
            { id: "urgamal", name: "Ургамал" },
            { id: "yaruu", name: "Яруу" },
            { id: "tsagaankhairkhan", name: "Цагаанхайрхан" },
            { id: "tsagaanchuluut", name: "Цагаанчулуут" },
            { id: "tsetsen_uul", name: "Цэцэн-Уул" },
            { id: "shilUustei", name: "Шилүүстэй" },
            { id: "erdenekhairkhan", name: "Эрдэнэхайрхан" },
        ],
    },
    {
        id: "orkhon",
        name: "Орхон",
        soums: [
            { id: "bayan_ondor", name: "Баян-Өндөр" },
            { id: "jargalant", name: "Жаргалант" },
        ],
    },
    {
        id: "ovorkhangai",
        name: "Өвөрхангай",
        soums: [
            { id: "aruaykheer", name: "Арвайхээр" },
            { id: "baruunbayan_ulaan", name: "Баруунбаян-Улаан" },
            { id: "bat_olzii", name: "Бат-Өлзий" },
            { id: "bayan_ondor", name: "Баян-Өндөр" },
            { id: "bayangol", name: "Баянгол" },
            { id: "bogd", name: "Богд" },
            { id: "burd", name: "Бүрд" },
            { id: "guulin", name: "Гучин-Ус" },
            { id: "yesonzuil", name: "Есөнзүйл" },
            { id: "zuunbayan_ulaan", name: "Зүүнбаян-Улаан" },
            { id: "nariinteel", name: "Нарийнтээл" },
            { id: "olziit", name: "Өлзийт" },
            { id: "sant", name: "Сант" },
            { id: "taragt", name: "Тарагт" },
            { id: "togs", name: "Төгрөг" },
            { id: "uyanga", name: "Уянга" },
            { id: "khairkhandulaan", name: "Хайрхандулаан" },
            { id: "hujirt", name: "Хужирт" },
            { id: "harhorin", name: "Хархорин" },
        ],
    },
    {
        id: "omnugovi",
        name: "Өмнөговь",
        soums: [
            { id: "bayandalai", name: "Баяндалай" },
            { id: "bayan_ovoo", name: "Баян-Овоо" },
            { id: "bulgan", name: "Булган" },
            { id: "gurvantes", name: "Гурвантэс" },
            { id: "dalanzadgad", name: "Даланзадгад" },
            { id: "mandal_ovoo", name: "Мандал-Овоо" },
            { id: "manlai", name: "Манлай" },
            { id: "noyon", name: "Ноён" },
            { id: "nomgon", name: "Нөмгөн" },
            { id: "sevrei", name: "Сэврэй" },
            { id: "khanbogd", name: "Ханбогд" },
            { id: "khan_hongor", name: "Ханхонгор" },
            { id: "khurmen", name: "Хүрмэн" },
            { id: "tsogt_ovoo", name: "Цогт-Овоо" },
            { id: "tsogttsetsii", name: "Цогтцэций" },
        ],
    },
    {
        id: "sukhbaatar",
        name: "Сүхбаатар",
        soums: [
            { id: "asgat", name: "Асгат" },
            { id: "baruun_urt", name: "Баруун-Урт" },
            { id: "bayandelger", name: "Баяндэлгэр" },
            { id: "dariganga", name: "Дарьганга" },
            { id: "monkhkhaan", name: "Мөнххаан" },
            { id: "naran", name: "Наран" },
            { id: "ongon", name: "Онгон" },
            { id: "sukhbaatar", name: "Сүхбаатар" },
            { id: "tuvshinshiree", name: "Түвшинширээ" },
            { id: "tumentsogt", name: "Түмэнцогт" },
            { id: "uulbayan", name: "Уулбаян" },
            { id: "halzan", name: "Халзан" },
            { id: "erdenetsagaan", name: "Эрдэнэцагаан" },
        ],
    },
    {
        id: "selenge",
        name: "Сэлэнгэ",
        soums: [
            { id: "altanbulag", name: "Алтанбулаг" },
            { id: "baruunburen", name: "Баруунбүрэн" },
            { id: "bayangol", name: "Баянгол" },
            { id: "javkhlant", name: "Жавхлант" },
            { id: "zuunburen", name: "Зүүнбүрэн" },
            { id: "mandal", name: "Мандал" },
            { id: "orkhon", name: "Орхон" },
            { id: "orkhontuul", name: "Орхонтуул" },
            { id: "saikhan", name: "Сайхан" },
            { id: "sant", name: "Сант" },
            { id: "sukhbaatar", name: "Сүхбаатар" },
            { id: "tushig", name: "Түшиг" },
            { id: "khuder", name: "Хүдэр" },
            { id: "khutag", name: "Хушаат" },
            { id: "tsagaannuur", name: "Цагааннуур" },
            { id: "shaamar", name: "Шаамар" },
            { id: "eru", name: "Ерөө" },
            { id: "khutul", name: "Хөтөл" }, // Tosgon
            { id: "tunkhel", name: "Түнхэл" }, // Tosgon
            { id: "kherkh", name: "Хэрх" }, // Tosgon
            { id: "bugant", name: "Бугант" }, // Tosgon
            { id: "dulaankhaan", name: "Дулаанхаан" }, // Tosgon
        ],
    },
    {
        id: "tov",
        name: "Төв",
        soums: [
            { id: "altanbulag", name: "Алтанбулаг" },
            { id: "argalant", name: "Аргалант" },
            { id: "ar_khustai", name: "Архуст" },
            { id: "batsumber", name: "Батсүмбэр" },
            { id: "bayan", name: "Баян" },
            { id: "bayan_onjuul", name: "Баян-Өнжүүл" },
            { id: "bayandelger", name: "Баяндэлгэр" },
            { id: "bayanjargalan", name: "Баянжаргалан" },
            { id: "bayanchandmani", name: "Баянчандмань" },
            { id: "bayantsagaan", name: "Баянцагаан" },
            { id: "bayantsogt", name: "Баянцогт" },
            { id: "bornuur", name: "Борнуур" },
            { id: "buren", name: "Бүрэн" },
            { id: "delgerkhaan", name: "Дэлгэрхаан" },
            { id: "zaamar", name: "Заамар" },
            { id: "zuunmod", name: "Зуунмод" },
            { id: "jargalant", name: "Жаргалант" },
            { id: "lung", name: "Лүн" },
            { id: "mongonmorit", name: "Мөнгөнморьт" },
            { id: "ondorshireet", name: "Өндөрширээт" },
            { id: "sergelen", name: "Сэргэлэн" },
            { id: "sumber", name: "Сүмбэр" },
            { id: "tseel", name: "Цээл" },
            { id: "ugtaal", name: "Угтаалцайдам" },
            { id: "khangai", name: "Эрдэнэ" },
            { id: "erdenesant", name: "Эрдэнэсант" },
            { id: "bayan_tsogt", name: "Баянцогт" },
        ],
    },
    {
        id: "uvs",
        name: "Увс",
        soums: [
            { id: "baruunturuun", name: "Баруунтуруун" },
            { id: "bokhmoron", name: "Бөхмөрөн" },
            { id: "davst", name: "Давст" },
            { id: "zavkhan", name: "Завхан" },
            { id: "zuungobi", name: "Зүүнговь" },
            { id: "zuunkhangai", name: "Зүүнхангай" },
            { id: "malchin", name: "Малчин" },
            { id: "naranbulag", name: "Наранбулаг" },
            { id: "olgii", name: "Өлгий" },
            { id: "omnogobi", name: "Өмнөговь" },
            { id: "ondorkhangai", name: "Өндөрхангай" },
            { id: "sagil", name: "Сагил" },
            { id: "tarialan", name: "Тариалан" },
            { id: "tes", name: "Тэс" },
            { id: "ulaangom", name: "Улаангом" },
            { id: "khyargas", name: "Хяргас" },
            { id: "tsagaankhairkhan", name: "Цагаанхайрхан" },
            { id: "turgen", name: "Түргэн" },
            { id: "khovd", name: "Ховд" },
        ],
    },
    {
        id: "khovd",
        name: "Ховд",
        soums: [
            { id: "altai", name: "Алтай" },
            { id: "bulgan", name: "Булган" },
            { id: "buyant", name: "Буянт" },
            { id: "darvi", name: "Дарви" },
            { id: "durgun", name: "Дөргөн" },
            { id: "duut", name: "Дуут" },
            { id: "zereg", name: "Зэрэг" },
            { id: "jargalant", name: "Жаргалант" },
            { id: "mankhan", name: "Манхан" },
            { id: "monkhkhairkhan", name: "Мөнххайрхан" },
            { id: "most", name: "Мөст" },
            { id: "myangad", name: "Мянгад" },
            { id: "uyench", name: "Үенч" },
            { id: "khovd", name: "Ховд" },
            { id: "tsetseg", name: "Цэцэг" },
            { id: "chandmani", name: "Чандмань" },
            { id: "erdeneburen", name: "Эрдэнэбүрэн" },
        ],
    },
    {
        id: "khuvsgul",
        name: "Хөвсгөл",
        soums: [
            { id: "alag_erdene", name: "Алаг-Эрдэнэ" },
            { id: "arbulag", name: "Арбулаг" },
            { id: "bayanzurkh", name: "Баянзүрх" },
            { id: "burentogtokh", name: "Бүрэнтогтох" },
            { id: "galuut", name: "Галт" },
            { id: "jargalant", name: "Жаргалант" },
            { id: "ikh_uul", name: "Их-Уул" },
            { id: "miron", name: "Мөрөн" },
            { id: "rashaant", name: "Рашаант" },
            { id: "renchinlhumbe", name: "Рэнчинлхүмбэ" },
            { id: "tarialan", name: "Тариалан" },
            { id: "tosontsengel", name: "Тосонцэнгэл" },
            { id: "tumurbulag", name: "Төмөрбулаг" },
            { id: "tunel", name: "Түнэл" },
            { id: "ulaan_uul", name: "Улаан-Уул" },
            { id: "khankh", name: "Ханх" },
            { id: "khatgal", name: "Хатгал" },
            { id: "tsagaan_uul", name: "Цагаан-Уул" },
            { id: "tsagaan_uur", name: "Цагаан-Үүр" },
            { id: "tsagaannuur", name: "Цагааннуур" },
            { id: "tsetserleg", name: "Цэцэрлэг" },
            { id: "chandmani_ondor", name: "Чандмань-Өндөр" },
            { id: "shine_ider", name: "Шинэ-Идэр" },
            { id: "erdenebulgan", name: "Эрдэнэбулган" },
        ],
    },
    {
        id: "khentii",
        name: "Хэнтий",
        soums: [
            { id: "batnorov", name: "Батноров" },
            { id: "batshireet", name: "Батширээт" },
            { id: "bayan_adraga", name: "Баян-Адрага" },
            { id: "bayanhutag", name: "Баянхутаг" },
            { id: "bayan_ovoo", name: "Баян-Овоо" },
            { id: "bayanmunkh", name: "Баянмөнх" },
            { id: "berkh", name: "Бэрх" }, // Tosgon
            { id: "bor_ondor", name: "Бор-Өндөр" }, // Tosgon
            { id: "galshar", name: "Галшар" },
            { id: "dadal", name: "Дадал" },
            { id: "darkhan", name: "Дархан" },
            { id: "delgerkhaan", name: "Дэлгэрхаан" },
            { id: "jargaltkhaan", name: "Жаргалтхаан" },
            { id: "kherlen", name: "Хэрлэн" },
            { id: "murun", name: "Мөрөн" },
            { id: "norovlin", name: "Норовлин" },
            { id: "omdelger", name: "Өмнөдэлгэр" },
            { id: "tsenkhermandal", name: "Цэнхэрмандал" },
            { id: "chingis", name: "Чингис" },
        ],
    },
];

export const CATEGORIES = [
    { id: "all", name: "Бүх", icon: "Package" },
    { id: "vegetables", name: "Хүнсний ногоо", icon: "Carrot" },
    { id: "dairy", name: "Цагаан идээ", icon: "Milk" },
    { id: "meat", name: "Мах, махан бүтээгдэхүүн", icon: "Beef" },
    { id: "berries_honey", name: "Жимс, Зөгийн бал", icon: "Cherry" },
    { id: "bakery", name: "Гурил, Боов", icon: "Croissant" },
    { id: "drinks", name: "Айраг, Ундаа", icon: "Wine" },
    { id: "sewing", name: "Оёдол, Эсгий урлал", icon: "Shirt" },
    { id: "leather", name: "Арьс шир, Гутал", icon: "Footprints" },
    { id: "wool", name: "Ноос, Ноолуур", icon: "Scissors" },
    { id: "wood", name: "Мод, Гэр ахуй", icon: "Home" },
    { id: "crafts", name: "Гар урлал, Бэлэг", icon: "Gem" },
    { id: "livestock", name: "Мал аж ахуй", icon: "Dog" },
    { id: "raw_materials", name: "Түүхий эд, Тэжээл", icon: "Box" },
    { id: "services", name: "Тээвэр, Үйлчилгээ", icon: "Truck" },
];

// Mongolian grammar map for correct genitive (possessive) forms
export const CATEGORY_GRAMMAR: Record<string, string> = {
    "Хүнсний ногоо": "хүнсний ногооны",
    "Цагаан идээ": "цагаан идээний",
    "Мах, махан бүтээгдэхүүн": "мах, махан",
    "Жимс, Зөгийн бал": "жимс, зөгийн балын",
    "Гурил, Боов": "гурил, боовны",
    "Айраг, Ундаа": "айраг, ундааны",
    "Оёдол, Эсгий урлал": "оёдол, эсгий урлалын",
    "Арьс шир, Гутал": "арьс шир, гутлын",
    "Ноос, Ноолуур": "ноос, ноолуурын",
    "Мод, Гэр ахуй": "мод, гэр ахуйн",
    "Гар урлал, Бэлэг": "гар урлал, бэлэг дурсгалын",
    "Мал аж ахуй": "мал аж ахуйн",
    "Түүхий эд, Тэжээл": "түүхий эд, тэжээлийн",
    "Тээвэр, Үйлчилгээ": "тээвэр, үйлчилгээний",
    "Бүх": "төрлийн"
};

export interface Product {
    id: string;
    title: string;
    price: number;
    currency: string;
    location: { aimag: string; soum: string };
    image: string;
    category: string;
    seller: {
        name: string;
        phone: string;
        image?: string;
        isVerified?: boolean;
        isBusiness?: boolean;
        companyName?: string;
        companyLogo?: string;
        bankName?: string;
        bankAccount?: string;
        bankIBAN?: string;
    };
    createdAt: string;
    isFeatured?: boolean;
    subscriptionTier?: string;
    tier?: 'soum' | 'aimag' | 'national';
    views?: number;
    saves?: number;
    callClicks?: number;
    chatClicks?: number;
    shares?: number;
}

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        title: "Архангайн шинэ ааруул",
        price: 25000,
        currency: "₮",
        location: { aimag: "Архангай", soum: "Тариат" },
        image: "https://images.unsplash.com/photo-1627483262268-9c96d8a31892?w=800&auto=format&fit=crop&q=60",
        category: "dairy",
        seller: {
            name: "Бат-Эрдэнэ",
            phone: "99112233",
            isVerified: true,
            image: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=800&auto=format&fit=crop&q=60",
            isBusiness: true,
            companyName: "Victory Cars",
            companyLogo: "https://placehold.co/100x50/orange/white?text=VICTORY",
            bankName: "Хаан банк",
            bankAccount: "5000123456"
        },
        createdAt: "2025-12-01T10:00:00Z",
        isFeatured: true,
        subscriptionTier: "business",
        // Trending Stats
        views: 250,
        saves: 45,
        callClicks: 32,
        chatClicks: 18,
        shares: 12,
    },
    {
        id: "2",
        title: "Шинэ ургацын лууван",
        price: 3500,
        currency: "₮",
        location: { aimag: "Дархан-Уул", soum: "Хонгор" },
        image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800&auto=format&fit=crop&q=60",
        category: "vegetables",
        seller: {
            name: "Туяа",
            phone: "88776655",
            isVerified: true,
            image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=60"
        },
        createdAt: "2025-12-02T14:30:00Z",
        subscriptionTier: "basic",
        // Trending Stats
        views: 180,
        saves: 28,
        callClicks: 15,
        chatClicks: 9,
        shares: 5,
    },
    {
        id: "4",
        title: "Адууны мах (бүхлээр)",
        price: 1200000,
        currency: "₮",
        location: { aimag: "Архангай", soum: "Батцэнгэл" },
        image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&auto=format&fit=crop&q=60",
        category: "meat",
        seller: {
            name: "Дорж",
            phone: "99119911",
            isVerified: true,
            image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=60"
        },
        createdAt: "2025-11-20T18:00:00Z", // Older date
        isFeatured: true,
        subscriptionTier: "business",
        // Trending Stats
        views: 95,
        saves: 12,
        callClicks: 8,
        chatClicks: 3,
        shares: 2,
    },
];

export const MOCK_PRODUCERS = [
    {
        id: "p1",
        name: "Архангай Цагаан Идээ",
        location: { aimag: "Архангай", soum: "Тариат" },
        image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&auto=format&fit=crop&q=60",
        products: ["Ааруул", "Бяслаг"],
        rating: 4.8,
        isFamous: true,
    },
    {
        id: "p2",
        name: "Дархан Хүлэмж",
        location: { aimag: "Дархан-Уул", soum: "Хонгор" },
        image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&auto=format&fit=crop&q=60",
        products: ["Лууван", "Төмс"],
        rating: 4.5,
        isFamous: true,
    },
    {
        id: "p3",
        name: "Увс Чацаргана",
        location: { aimag: "Увс", soum: "Улаангом" },
        image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=60",
        products: ["Шүүс", "Тос"],
        rating: 4.9,
        isFamous: true,
    },
    {
        id: "p4",
        name: "Хэнтий Зөгийн Бал",
        location: { aimag: "Хэнтий", soum: "Батноров" },
        image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=60",
        products: ["Зөгийн бал"],
        rating: 4.7,
        isFamous: true,
    },
];

export const MOCK_REQUESTS = [
    {
        id: "r1",
        userId: "u1",
        userName: "Дорж",
        userPhone: "99119911",
        businessName: "Дорж Мах",
        location: "Архангай, Батцэнгэл",
        status: "pending", // pending, approved, rejected
        date: "2023-11-27",
    },
    {
        id: "r2",
        userId: "u2",
        userName: "Сараа",
        userPhone: "88112233",
        businessName: "Сараа Оёдол",
        location: "Улаанбаатар",
        status: "pending",
        date: "2023-11-26",
    },
    {
        id: "r3",
        userId: "u3",
        userName: "Баяр",
        userPhone: "99001122",
        businessName: "Баяр Газар Тариалан",
        location: "Сэлэнгэ, Мандал",
        status: "rejected",
        date: "2023-11-25",
    },
];

export const AIMAGS = locations;
